// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlEJoJbL2xE3eK_wDvQZa1qqrf7le8SOU',
    appId: '1:1068515401318:web:a445b383210045841c17a7',
    messagingSenderId: '1068515401318',
    projectId: 'recipe-b7d45',
    authDomain: 'recipe-b7d45.firebaseapp.com',
    storageBucket: 'recipe-b7d45.appspot.com',
    measurementId: 'G-1796MVTY9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNbILdduHV_k9qulEWk4iRl2aR-c2QDXA',
    appId: '1:1068515401318:android:7f37caa4f068cabf1c17a7',
    messagingSenderId: '1068515401318',
    projectId: 'recipe-b7d45',
    storageBucket: 'recipe-b7d45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaHe6Q4RytQYRZyUT3fozWyJbKqcHR5R8',
    appId: '1:1068515401318:ios:57fad203855124731c17a7',
    messagingSenderId: '1068515401318',
    projectId: 'recipe-b7d45',
    storageBucket: 'recipe-b7d45.appspot.com',
    iosClientId: '1068515401318-hfvf67cqd30o6ruvhlhog6qn7rfm70ve.apps.googleusercontent.com',
    iosBundleId: 'com.youce.recipeChef',
  );
}
